before_commands:
    - 'wget -O /tmp/noviusos.xml http://raw.github.com/novius-os/ci/master/chiba2/phpcs/ruleset.xml'
filter:
    excluded_paths:
        - 'vendor/**'
        - 'static/**'
tools:
    php_code_sniffer:
        command: 'phpcs -n'
        config:
            standard: /tmp/noviusos.xml
    php_pdepend: true
    php_cpd:
        # Minimum number of identical lines (default: 5)
        min_lines: 5
        # Minimum number of identical tokens (default: 70)
        min_tokens: 80
